In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("DataSet.csv")

In [ ]:
df.shape

(9082, 3925)

In [ ]:
df.head()

,Unnamed: 0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0

In [ ]:
df.tail(20)

,Unnamed: 0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
9062,9063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,3,3,0,0,0,1
9063,9064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,1,3,1,0,1,1,1
9064,9065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,1
9065,9066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,1
9066,9067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,1,0,0,0,1
9067,9068,0.5,NaN,0.5,0.36,NaN,0.36,0.5,NaN,0.5,...,0,1,0,0,1,0,1,0,0,1
9068,9069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,0,2,2,0,0,0,1
9069,9070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,1,0,4,0,1,3,0,1
9070,9071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,1
9071,9072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,0,1,0,0,0,0,1
9072,9073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,1,0,3,3,0,0,0,1
9073,9074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,1
9074,9075,0.0,0.0,NaN,0.00,0.0,NaN,NaN,NaN,NaN,...,0,1,0,0,3,0,0,3,0,1
9075,9076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,1,0,2,0,2,0,0,1
9076,9077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,1,0,5,4,0,1,0,1
9077,9078,0.5,NaN,0.5,0.50,NaN,0.50,NaN,NaN,NaN,...,0,1,0,0,1,1,0,0,0,1
9078,9079,1.0,NaN,1.0,1.00,NaN,1.00,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,1
9079,9080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,1,0,0,0,1
9080,9081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,1
9081,9082,0.0,NaN,0.0,0.00,NaN,0.00,NaN,NaN,NaN,...,0,1,0,0,1,0,0,0,0,1

In [ ]:
df.isnull().sum()

Unnamed: 0       0
F1            6491
F2            7550
F3            7634
F4            6491
              ...
F3920            0
F3921            0
F3922            0
F3923            0
F3924            0
Length: 3925, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9082 entries, 0 to 9081
Columns: 3925 entries, Unnamed: 0 to F3924
dtypes: float64(3876), int64(41), object(8)
memory usage: 272.0+ MB

In [ ]:
df.describe()

,Unnamed: 0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
count,9082.000000,2591.000000,1532.000000,1448.000000,2591.000000,1532.000000,1448.000000,855.000000,488.000000,725.000000,...,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000,9082.000000
mean,4541.500000,0.679722,0.656129,0.724731,0.691721,0.659497,0.727811,0.487135,0.441844,0.508676,...,0.002532,0.780335,0.213719,0.020921,1.280775,0.210636,0.336930,0.562431,0.066505,0.008919
std,2621.891906,0.392573,0.398420,0.408869,0.401105,0.404242,0.413717,0.399929,0.435882,0.398278,...,0.050263,0.414043,0.409954,0.143126,1.008499,0.569385,0.647817,0.761297,0.325110,0.094022
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2271.250000,0.430000,0.330000,0.500000,0.380000,0.320000,0.430000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4541.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,0.330000,0.500000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6811.750000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,9082.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,27.000000,14.000000,11.000000,18.000000,6.000000,1.000000

In [ ]:
df =  df.drop(columns=["Unnamed: 0"])

In [ ]:
df

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F3915,F3916,F3917,F3918,F3919,F3920,F3921,F3922,F3923,F3924
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9077,0.5,NaN,0.5,0.5,NaN,0.5,NaN,NaN,NaN,NaN,...,0,1,0,0,1,1,0,0,0,1
9078,1.0,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,1,0,0,1
9079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,1,0,0,0,1
9080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,1,0,1
9081,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,...,0,1,0,0,1,0,0,0,0,1

In [ ]:
df["F3924"].value_counts()

F3924
0    9001
1      81
Name: count, dtype: int64

In [ ]:
df

NameError: name 'df' is not defined